### ISSUE TITLE
Expand Only One Header

### ISSUE THREAD

**Issue by abedi-reza** [touchlane/CampcotCollectionView#1]
How expand only one header?

**Comment by josipbernat** [comment]
This is good question. Is there an option to do this?

**Comment by aznelite89** [comment]
I wonder too

**Comment by Myryx** [comment]
If you all looked at the code, you'd see that he basically has 2 layouts: expanded and collapsed and he transitions between them. I suppose having this functionality for specific sections would complicate everything immensely, so...

**Comment by pkandrashkou** [comment]
Thanks @abedi-reza for creating an issue. Currently there are no plans to extend functionality to support expanding of selected section. The idea behind this implementation is to have a lightweight solution. 
Pull requests are always warmly welcome, so you can go ahead and try out some ways to achieve the desired behavior 👍
