### ISSUE TITLE
Bug: state of self.isExpanded is incorrect on startup

### ISSUE THREAD

**Issue by 224XS** [touchlane/CampcotCollectionView#16]
Nice package and it mostly works fine but,
Using this package causes the following
1) the collectionView starts as open despite calling view.collapse in ViewWillAppear
2) user needs to tap a header twice (only the first time) to collapse the collection. After the first collapse, the sections accordion appropriately with a single tap.

Finding: in calling the method "collapse" the first time, when app opens, the internal flag "isExpanded" is set to false despite the collection being defaulted to fully expanded.

I can not find where you initialize your isExpanded var, but you should probably have an optional init which passes the desired state.

**Comment by MaziarBarzi** [comment]
anjam shod

**Comment by VadzimMarozau** [comment]
`isExpanded` parameter is added to init
https://github.com/touchlane/CampcotCollectionView/releases/tag/0.0.8
