### ISSUE TITLE
Swift 4.2 update needed - obseleted code referenced

### ISSUE THREAD

**Issue by barfoon** [touchlane/CampcotCollectionView#2]
![image](https://user-images.githubusercontent.com/1120510/51780795-a59f7f00-20df-11e9-9b20-65b274629dc9.png)

**Comment by pkandrashkou** [comment]
@barfoon Thank you for pointing this out!  I have created PR that updates the code base to the swift 4.2. New version of the library will be available as soon as PR is merged to the master.
