### ISSUE TITLE
Support storyboard

### ISSUE THREAD

**Issue by tony-hoang999** [touchlane/CampcotCollectionView#8]
Hello,
I tried to use the CampcotCollectionView in storyboard but couldn't. I ran into this error
```
required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
}
```
Could you please help fix that. Thank you!

**Comment by AlexYanski** [comment]
@tony-hoang999 Hello! Thanks for your feedback! Now the issue is resolved in 0.0.7 release.
Check out new readme about how to setup storyboard based CampcotCollectionView.
